require('user.options')
require('user.keymaps')
require('user.plugins')
require('user.colorscheme')
require('user.cmp')
require('user.lsp.mason')
require('user.lsp.lspsaga')
require('user.lsp.lspconfig')
require('user.lsp.null-ls')
require('user.telescope')
require('user.treesitter')
require('user.discord')
require('user.autopairs')
require('user.comment')
require('user.gitsigns')
require('user.nvim-tree')
require('user.bufferline')
require('user.toggleterm')
require('user.lualine')
require('user.project')
require('user.impatient')
require('user.indent-blankline')
require('user.alpha')


